package com.example.wiki.domain;

/**
 * Database Table Remarks:
 *   电子书
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ebook
 */
public class Ebook {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   分类1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.category1_id
     *
     * @mbg.generated
     */
    private Long category1Id;

    /**
     * Database Column Remarks:
     *   分类2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.category2_id
     *
     * @mbg.generated
     */
    private Long category2Id;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   封面
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     * Database Column Remarks:
     *   文档数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.doc_count
     *
     * @mbg.generated
     */
    private Integer docCount;

    /**
     * Database Column Remarks:
     *   阅读数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.view_count
     *
     * @mbg.generated
     */
    private Integer viewCount;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ebook.vote_count
     *
     * @mbg.generated
     */
    private Integer voteCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.id
     *
     * @return the value of ebook.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.id
     *
     * @param id the value for ebook.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.name
     *
     * @return the value of ebook.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.name
     *
     * @param name the value for ebook.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.category1_id
     *
     * @return the value of ebook.category1_id
     *
     * @mbg.generated
     */
    public Long getCategory1Id() {
        return category1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.category1_id
     *
     * @param category1Id the value for ebook.category1_id
     *
     * @mbg.generated
     */
    public void setCategory1Id(Long category1Id) {
        this.category1Id = category1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.category2_id
     *
     * @return the value of ebook.category2_id
     *
     * @mbg.generated
     */
    public Long getCategory2Id() {
        return category2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.category2_id
     *
     * @param category2Id the value for ebook.category2_id
     *
     * @mbg.generated
     */
    public void setCategory2Id(Long category2Id) {
        this.category2Id = category2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.description
     *
     * @return the value of ebook.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.description
     *
     * @param description the value for ebook.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.cover
     *
     * @return the value of ebook.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.cover
     *
     * @param cover the value for ebook.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.doc_count
     *
     * @return the value of ebook.doc_count
     *
     * @mbg.generated
     */
    public Integer getDocCount() {
        return docCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.doc_count
     *
     * @param docCount the value for ebook.doc_count
     *
     * @mbg.generated
     */
    public void setDocCount(Integer docCount) {
        this.docCount = docCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.view_count
     *
     * @return the value of ebook.view_count
     *
     * @mbg.generated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.view_count
     *
     * @param viewCount the value for ebook.view_count
     *
     * @mbg.generated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ebook.vote_count
     *
     * @return the value of ebook.vote_count
     *
     * @mbg.generated
     */
    public Integer getVoteCount() {
        return voteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ebook.vote_count
     *
     * @param voteCount the value for ebook.vote_count
     *
     * @mbg.generated
     */
    public void setVoteCount(Integer voteCount) {
        this.voteCount = voteCount;
    }
}