package com.example.wiki.domain;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   轮播图
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table index_img
 */
public class IndexImg {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.img_id
     *
     * @mbg.generated
     */
    private String imgId;

    /**
     * Database Column Remarks:
     *   图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     * Database Column Remarks:
     *   背景色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.img_bg_color
     *
     * @mbg.generated
     */
    private String imgBgColor;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.prod_id
     *
     * @mbg.generated
     */
    private String prodId;

    /**
     * Database Column Remarks:
     *   商品分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.category_id
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     * Database Column Remarks:
     *   轮播图类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.index_type
     *
     * @mbg.generated
     */
    private Integer indexType;

    /**
     * Database Column Remarks:
     *   轮播图展示顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.seq
     *
     * @mbg.generated
     */
    private Integer seq;

    /**
     * Database Column Remarks:
     *   是否展示：1正常显示 0下线
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_img.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.img_id
     *
     * @return the value of index_img.img_id
     *
     * @mbg.generated
     */
    public String getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.img_id
     *
     * @param imgId the value for index_img.img_id
     *
     * @mbg.generated
     */
    public void setImgId(String imgId) {
        this.imgId = imgId == null ? null : imgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.img_url
     *
     * @return the value of index_img.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.img_url
     *
     * @param imgUrl the value for index_img.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.img_bg_color
     *
     * @return the value of index_img.img_bg_color
     *
     * @mbg.generated
     */
    public String getImgBgColor() {
        return imgBgColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.img_bg_color
     *
     * @param imgBgColor the value for index_img.img_bg_color
     *
     * @mbg.generated
     */
    public void setImgBgColor(String imgBgColor) {
        this.imgBgColor = imgBgColor == null ? null : imgBgColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.prod_id
     *
     * @return the value of index_img.prod_id
     *
     * @mbg.generated
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.prod_id
     *
     * @param prodId the value for index_img.prod_id
     *
     * @mbg.generated
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.category_id
     *
     * @return the value of index_img.category_id
     *
     * @mbg.generated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.category_id
     *
     * @param categoryId the value for index_img.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.index_type
     *
     * @return the value of index_img.index_type
     *
     * @mbg.generated
     */
    public Integer getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.index_type
     *
     * @param indexType the value for index_img.index_type
     *
     * @mbg.generated
     */
    public void setIndexType(Integer indexType) {
        this.indexType = indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.seq
     *
     * @return the value of index_img.seq
     *
     * @mbg.generated
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.seq
     *
     * @param seq the value for index_img.seq
     *
     * @mbg.generated
     */
    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.status
     *
     * @return the value of index_img.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.status
     *
     * @param status the value for index_img.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.create_time
     *
     * @return the value of index_img.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.create_time
     *
     * @param createTime the value for index_img.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_img.update_time
     *
     * @return the value of index_img.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_img.update_time
     *
     * @param updateTime the value for index_img.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}