package com.example.wiki.domain;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   订单
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orders
 */
public class Orders {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.untitled
     *
     * @mbg.generated
     */
    private String untitled;

    /**
     * Database Column Remarks:
     *   收货人快照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     * Database Column Remarks:
     *   收货人手机号码快照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     * Database Column Remarks:
     *   收货地址快照
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     * Database Column Remarks:
     *   订单总价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_amount
     *
     * @mbg.generated
     */
    private String totalAmount;

    /**
     * Database Column Remarks:
     *   实际支付总价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_amount
     *
     * @mbg.generated
     */
    private String actualAmount;

    /**
     * Database Column Remarks:
     *   支付方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     * Database Column Remarks:
     *   订单备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_remark
     *
     * @mbg.generated
     */
    private String orderRemark;

    /**
     * Database Column Remarks:
     *   订单状态：1待付款 2待发货 3待收货 4待评价  5已完成  6已关闭
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   配送方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_type
     *
     * @mbg.generated
     */
    private String deliveryType;

    /**
     * Database Column Remarks:
     *   物流单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_flow_id
     *
     * @mbg.generated
     */
    private String deliveryFlowId;

    /**
     * Database Column Remarks:
     *   订单运费
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_freight
     *
     * @mbg.generated
     */
    private String orderFreight;

    /**
     * Database Column Remarks:
     *   逻辑删除状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delete_status
     *
     * @mbg.generated
     */
    private Integer deleteStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * Database Column Remarks:
     *   付款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_time
     *
     * @mbg.generated
     */
    private LocalDateTime payTime;

    /**
     * Database Column Remarks:
     *   发货时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.delivery_time
     *
     * @mbg.generated
     */
    private LocalDateTime deliveryTime;

    /**
     * Database Column Remarks:
     *   完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.flish_time
     *
     * @mbg.generated
     */
    private LocalDateTime flishTime;

    /**
     * Database Column Remarks:
     *   取消时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.cancel_time
     *
     * @mbg.generated
     */
    private LocalDateTime cancelTime;

    /**
     * Database Column Remarks:
     *   订单关闭类型：1超时未支付 2退款关闭 4买家取消 15已通过货到付款交易
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.close_type
     *
     * @mbg.generated
     */
    private Integer closeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_id
     *
     * @return the value of orders.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_id
     *
     * @param orderId the value for orders.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.untitled
     *
     * @return the value of orders.untitled
     *
     * @mbg.generated
     */
    public String getUntitled() {
        return untitled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.untitled
     *
     * @param untitled the value for orders.untitled
     *
     * @mbg.generated
     */
    public void setUntitled(String untitled) {
        this.untitled = untitled == null ? null : untitled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_name
     *
     * @return the value of orders.receiver_name
     *
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_name
     *
     * @param receiverName the value for orders.receiver_name
     *
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_mobile
     *
     * @return the value of orders.receiver_mobile
     *
     * @mbg.generated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_mobile
     *
     * @param receiverMobile the value for orders.receiver_mobile
     *
     * @mbg.generated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.receiver_address
     *
     * @return the value of orders.receiver_address
     *
     * @mbg.generated
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.receiver_address
     *
     * @param receiverAddress the value for orders.receiver_address
     *
     * @mbg.generated
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_amount
     *
     * @return the value of orders.total_amount
     *
     * @mbg.generated
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_amount
     *
     * @param totalAmount the value for orders.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount == null ? null : totalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actual_amount
     *
     * @return the value of orders.actual_amount
     *
     * @mbg.generated
     */
    public String getActualAmount() {
        return actualAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actual_amount
     *
     * @param actualAmount the value for orders.actual_amount
     *
     * @mbg.generated
     */
    public void setActualAmount(String actualAmount) {
        this.actualAmount = actualAmount == null ? null : actualAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_type
     *
     * @return the value of orders.pay_type
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_type
     *
     * @param payType the value for orders.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_remark
     *
     * @return the value of orders.order_remark
     *
     * @mbg.generated
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_remark
     *
     * @param orderRemark the value for orders.order_remark
     *
     * @mbg.generated
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_type
     *
     * @return the value of orders.delivery_type
     *
     * @mbg.generated
     */
    public String getDeliveryType() {
        return deliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_type
     *
     * @param deliveryType the value for orders.delivery_type
     *
     * @mbg.generated
     */
    public void setDeliveryType(String deliveryType) {
        this.deliveryType = deliveryType == null ? null : deliveryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_flow_id
     *
     * @return the value of orders.delivery_flow_id
     *
     * @mbg.generated
     */
    public String getDeliveryFlowId() {
        return deliveryFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_flow_id
     *
     * @param deliveryFlowId the value for orders.delivery_flow_id
     *
     * @mbg.generated
     */
    public void setDeliveryFlowId(String deliveryFlowId) {
        this.deliveryFlowId = deliveryFlowId == null ? null : deliveryFlowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_freight
     *
     * @return the value of orders.order_freight
     *
     * @mbg.generated
     */
    public String getOrderFreight() {
        return orderFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_freight
     *
     * @param orderFreight the value for orders.order_freight
     *
     * @mbg.generated
     */
    public void setOrderFreight(String orderFreight) {
        this.orderFreight = orderFreight == null ? null : orderFreight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delete_status
     *
     * @return the value of orders.delete_status
     *
     * @mbg.generated
     */
    public Integer getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delete_status
     *
     * @param deleteStatus the value for orders.delete_status
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Integer deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_time
     *
     * @return the value of orders.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_time
     *
     * @param updateTime the value for orders.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_time
     *
     * @return the value of orders.pay_time
     *
     * @mbg.generated
     */
    public LocalDateTime getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_time
     *
     * @param payTime the value for orders.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(LocalDateTime payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.delivery_time
     *
     * @return the value of orders.delivery_time
     *
     * @mbg.generated
     */
    public LocalDateTime getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.delivery_time
     *
     * @param deliveryTime the value for orders.delivery_time
     *
     * @mbg.generated
     */
    public void setDeliveryTime(LocalDateTime deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.flish_time
     *
     * @return the value of orders.flish_time
     *
     * @mbg.generated
     */
    public LocalDateTime getFlishTime() {
        return flishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.flish_time
     *
     * @param flishTime the value for orders.flish_time
     *
     * @mbg.generated
     */
    public void setFlishTime(LocalDateTime flishTime) {
        this.flishTime = flishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.cancel_time
     *
     * @return the value of orders.cancel_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCancelTime() {
        return cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.cancel_time
     *
     * @param cancelTime the value for orders.cancel_time
     *
     * @mbg.generated
     */
    public void setCancelTime(LocalDateTime cancelTime) {
        this.cancelTime = cancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.close_type
     *
     * @return the value of orders.close_type
     *
     * @mbg.generated
     */
    public Integer getCloseType() {
        return closeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.close_type
     *
     * @param closeType the value for orders.close_type
     *
     * @mbg.generated
     */
    public void setCloseType(Integer closeType) {
        this.closeType = closeType;
    }
}