package com.example.wiki.domain;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   订单项/快照
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order_item
 */
public class OrderItem {
    /**
     * Database Column Remarks:
     *   订单项id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.item_id
     *
     * @mbg.generated
     */
    private String itemId;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_name
     *
     * @mbg.generated
     */
    private LocalDateTime productName;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_img
     *
     * @mbg.generated
     */
    private String productImg;

    /**
     * Database Column Remarks:
     *   skuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku_id
     *
     * @mbg.generated
     */
    private LocalDateTime skuId;

    /**
     * Database Column Remarks:
     *   sku名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sku_name
     *
     * @mbg.generated
     */
    private String skuName;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.product_price
     *
     * @mbg.generated
     */
    private String productPrice;

    /**
     * Database Column Remarks:
     *   购买数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buy_counts
     *
     * @mbg.generated
     */
    private String buyCounts;

    /**
     * Database Column Remarks:
     *   商品总金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.total_amount
     *
     * @mbg.generated
     */
    private String totalAmount;

    /**
     * Database Column Remarks:
     *   加入购物车时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.basket_data
     *
     * @mbg.generated
     */
    private String basketData;

    /**
     * Database Column Remarks:
     *   购买时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.buy_time
     *
     * @mbg.generated
     */
    private String buyTime;

    /**
     * Database Column Remarks:
     *   评论状态 0未评价 1已评价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.is_comment
     *
     * @mbg.generated
     */
    private String isComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.item_id
     *
     * @return the value of order_item.item_id
     *
     * @mbg.generated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.item_id
     *
     * @param itemId the value for order_item.item_id
     *
     * @mbg.generated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_id
     *
     * @return the value of order_item.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_id
     *
     * @param orderId the value for order_item.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_id
     *
     * @return the value of order_item.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_id
     *
     * @param productId the value for order_item.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_name
     *
     * @return the value of order_item.product_name
     *
     * @mbg.generated
     */
    public LocalDateTime getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_name
     *
     * @param productName the value for order_item.product_name
     *
     * @mbg.generated
     */
    public void setProductName(LocalDateTime productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_img
     *
     * @return the value of order_item.product_img
     *
     * @mbg.generated
     */
    public String getProductImg() {
        return productImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_img
     *
     * @param productImg the value for order_item.product_img
     *
     * @mbg.generated
     */
    public void setProductImg(String productImg) {
        this.productImg = productImg == null ? null : productImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sku_id
     *
     * @return the value of order_item.sku_id
     *
     * @mbg.generated
     */
    public LocalDateTime getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sku_id
     *
     * @param skuId the value for order_item.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(LocalDateTime skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sku_name
     *
     * @return the value of order_item.sku_name
     *
     * @mbg.generated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sku_name
     *
     * @param skuName the value for order_item.sku_name
     *
     * @mbg.generated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.product_price
     *
     * @return the value of order_item.product_price
     *
     * @mbg.generated
     */
    public String getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.product_price
     *
     * @param productPrice the value for order_item.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice == null ? null : productPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.buy_counts
     *
     * @return the value of order_item.buy_counts
     *
     * @mbg.generated
     */
    public String getBuyCounts() {
        return buyCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.buy_counts
     *
     * @param buyCounts the value for order_item.buy_counts
     *
     * @mbg.generated
     */
    public void setBuyCounts(String buyCounts) {
        this.buyCounts = buyCounts == null ? null : buyCounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.total_amount
     *
     * @return the value of order_item.total_amount
     *
     * @mbg.generated
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.total_amount
     *
     * @param totalAmount the value for order_item.total_amount
     *
     * @mbg.generated
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount == null ? null : totalAmount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.basket_data
     *
     * @return the value of order_item.basket_data
     *
     * @mbg.generated
     */
    public String getBasketData() {
        return basketData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.basket_data
     *
     * @param basketData the value for order_item.basket_data
     *
     * @mbg.generated
     */
    public void setBasketData(String basketData) {
        this.basketData = basketData == null ? null : basketData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.buy_time
     *
     * @return the value of order_item.buy_time
     *
     * @mbg.generated
     */
    public String getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.buy_time
     *
     * @param buyTime the value for order_item.buy_time
     *
     * @mbg.generated
     */
    public void setBuyTime(String buyTime) {
        this.buyTime = buyTime == null ? null : buyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.is_comment
     *
     * @return the value of order_item.is_comment
     *
     * @mbg.generated
     */
    public String getIsComment() {
        return isComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.is_comment
     *
     * @param isComment the value for order_item.is_comment
     *
     * @mbg.generated
     */
    public void setIsComment(String isComment) {
        this.isComment = isComment == null ? null : isComment.trim();
    }
}