package com.example.wiki.domain;

import java.time.LocalDateTime;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品规格
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_sku
 */
public class ProductSku {
    /**
     * Database Column Remarks:
     *   sku编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sku_id
     *
     * @mbg.generated
     */
    private String skuId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.product_id
     *
     * @mbg.generated
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   sku名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sku_name
     *
     * @mbg.generated
     */
    private String skuName;

    /**
     * Database Column Remarks:
     *   sku图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sku_img
     *
     * @mbg.generated
     */
    private String skuImg;

    /**
     * Database Column Remarks:
     *   属性组合
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.untitile
     *
     * @mbg.generated
     */
    private String untitile;

    /**
     * Database Column Remarks:
     *   原价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.original_price
     *
     * @mbg.generated
     */
    private String originalPrice;

    /**
     * Database Column Remarks:
     *   销售价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.sell_price
     *
     * @mbg.generated
     */
    private String sellPrice;

    /**
     * Database Column Remarks:
     *   折扣力度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.discounts
     *
     * @mbg.generated
     */
    private String discounts;

    /**
     * Database Column Remarks:
     *   库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.stock
     *
     * @mbg.generated
     */
    private String stock;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   sku状态：1启用 0禁用 -1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_sku.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sku_id
     *
     * @return the value of product_sku.sku_id
     *
     * @mbg.generated
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sku_id
     *
     * @param skuId the value for product_sku.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.product_id
     *
     * @return the value of product_sku.product_id
     *
     * @mbg.generated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.product_id
     *
     * @param productId the value for product_sku.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sku_name
     *
     * @return the value of product_sku.sku_name
     *
     * @mbg.generated
     */
    public String getSkuName() {
        return skuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sku_name
     *
     * @param skuName the value for product_sku.sku_name
     *
     * @mbg.generated
     */
    public void setSkuName(String skuName) {
        this.skuName = skuName == null ? null : skuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sku_img
     *
     * @return the value of product_sku.sku_img
     *
     * @mbg.generated
     */
    public String getSkuImg() {
        return skuImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sku_img
     *
     * @param skuImg the value for product_sku.sku_img
     *
     * @mbg.generated
     */
    public void setSkuImg(String skuImg) {
        this.skuImg = skuImg == null ? null : skuImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.untitile
     *
     * @return the value of product_sku.untitile
     *
     * @mbg.generated
     */
    public String getUntitile() {
        return untitile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.untitile
     *
     * @param untitile the value for product_sku.untitile
     *
     * @mbg.generated
     */
    public void setUntitile(String untitile) {
        this.untitile = untitile == null ? null : untitile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.original_price
     *
     * @return the value of product_sku.original_price
     *
     * @mbg.generated
     */
    public String getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.original_price
     *
     * @param originalPrice the value for product_sku.original_price
     *
     * @mbg.generated
     */
    public void setOriginalPrice(String originalPrice) {
        this.originalPrice = originalPrice == null ? null : originalPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.sell_price
     *
     * @return the value of product_sku.sell_price
     *
     * @mbg.generated
     */
    public String getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.sell_price
     *
     * @param sellPrice the value for product_sku.sell_price
     *
     * @mbg.generated
     */
    public void setSellPrice(String sellPrice) {
        this.sellPrice = sellPrice == null ? null : sellPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.discounts
     *
     * @return the value of product_sku.discounts
     *
     * @mbg.generated
     */
    public String getDiscounts() {
        return discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.discounts
     *
     * @param discounts the value for product_sku.discounts
     *
     * @mbg.generated
     */
    public void setDiscounts(String discounts) {
        this.discounts = discounts == null ? null : discounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.stock
     *
     * @return the value of product_sku.stock
     *
     * @mbg.generated
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.stock
     *
     * @param stock the value for product_sku.stock
     *
     * @mbg.generated
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.create_time
     *
     * @return the value of product_sku.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.create_time
     *
     * @param createTime the value for product_sku.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.update_time
     *
     * @return the value of product_sku.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.update_time
     *
     * @param updateTime the value for product_sku.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_sku.status
     *
     * @return the value of product_sku.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_sku.status
     *
     * @param status the value for product_sku.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}