package com.example.wiki.domain;

import java.time.LocalDateTime;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品评价
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_comments
 */
public class ProductComments {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.comm_id
     *
     * @mbg.generated
     */
    private String commId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   订单项
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.order_item_id
     *
     * @mbg.generated
     */
    private String orderItemId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   是否匿名：1是 0否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.is_anonymous
     *
     * @mbg.generated
     */
    private Integer isAnonymous;

    /**
     * Database Column Remarks:
     *   评价类型：1好评 0中评  -1差评
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.comm_type
     *
     * @mbg.generated
     */
    private Integer commType;

    /**
     * Database Column Remarks:
     *   评价等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.comm_level
     *
     * @mbg.generated
     */
    private Integer commLevel;

    /**
     * Database Column Remarks:
     *   评价类容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.comm_content
     *
     * @mbg.generated
     */
    private String commContent;

    /**
     * Database Column Remarks:
     *   评价晒图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.comm_imgs
     *
     * @mbg.generated
     */
    private String commImgs;

    /**
     * Database Column Remarks:
     *   评价时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.sepc_name
     *
     * @mbg.generated
     */
    private Date sepcName;

    /**
     * Database Column Remarks:
     *   是否回复：1已回复  0未回复
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.reply_status
     *
     * @mbg.generated
     */
    private Integer replyStatus;

    /**
     * Database Column Remarks:
     *   回复内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.reply_content
     *
     * @mbg.generated
     */
    private String replyContent;

    /**
     * Database Column Remarks:
     *   回复时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.reply_time
     *
     * @mbg.generated
     */
    private Date replyTime;

    /**
     * Database Column Remarks:
     *   是否显示：1是 0否
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_comments.is_show
     *
     * @mbg.generated
     */
    private Integer isShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.comm_id
     *
     * @return the value of product_comments.comm_id
     *
     * @mbg.generated
     */
    public String getCommId() {
        return commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.comm_id
     *
     * @param commId the value for product_comments.comm_id
     *
     * @mbg.generated
     */
    public void setCommId(String commId) {
        this.commId = commId == null ? null : commId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.product_id
     *
     * @return the value of product_comments.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.product_id
     *
     * @param productId the value for product_comments.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.product_name
     *
     * @return the value of product_comments.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.product_name
     *
     * @param productName the value for product_comments.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.order_item_id
     *
     * @return the value of product_comments.order_item_id
     *
     * @mbg.generated
     */
    public String getOrderItemId() {
        return orderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.order_item_id
     *
     * @param orderItemId the value for product_comments.order_item_id
     *
     * @mbg.generated
     */
    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId == null ? null : orderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.user_id
     *
     * @return the value of product_comments.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.user_id
     *
     * @param userId the value for product_comments.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.is_anonymous
     *
     * @return the value of product_comments.is_anonymous
     *
     * @mbg.generated
     */
    public Integer getIsAnonymous() {
        return isAnonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.is_anonymous
     *
     * @param isAnonymous the value for product_comments.is_anonymous
     *
     * @mbg.generated
     */
    public void setIsAnonymous(Integer isAnonymous) {
        this.isAnonymous = isAnonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.comm_type
     *
     * @return the value of product_comments.comm_type
     *
     * @mbg.generated
     */
    public Integer getCommType() {
        return commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.comm_type
     *
     * @param commType the value for product_comments.comm_type
     *
     * @mbg.generated
     */
    public void setCommType(Integer commType) {
        this.commType = commType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.comm_level
     *
     * @return the value of product_comments.comm_level
     *
     * @mbg.generated
     */
    public Integer getCommLevel() {
        return commLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.comm_level
     *
     * @param commLevel the value for product_comments.comm_level
     *
     * @mbg.generated
     */
    public void setCommLevel(Integer commLevel) {
        this.commLevel = commLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.comm_content
     *
     * @return the value of product_comments.comm_content
     *
     * @mbg.generated
     */
    public String getCommContent() {
        return commContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.comm_content
     *
     * @param commContent the value for product_comments.comm_content
     *
     * @mbg.generated
     */
    public void setCommContent(String commContent) {
        this.commContent = commContent == null ? null : commContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.comm_imgs
     *
     * @return the value of product_comments.comm_imgs
     *
     * @mbg.generated
     */
    public String getCommImgs() {
        return commImgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.comm_imgs
     *
     * @param commImgs the value for product_comments.comm_imgs
     *
     * @mbg.generated
     */
    public void setCommImgs(String commImgs) {
        this.commImgs = commImgs == null ? null : commImgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.sepc_name
     *
     * @return the value of product_comments.sepc_name
     *
     * @mbg.generated
     */
    public Date getSepcName() {
        return sepcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.sepc_name
     *
     * @param sepcName the value for product_comments.sepc_name
     *
     * @mbg.generated
     */
    public void setSepcName(Date sepcName) {
        this.sepcName = sepcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.reply_status
     *
     * @return the value of product_comments.reply_status
     *
     * @mbg.generated
     */
    public Integer getReplyStatus() {
        return replyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.reply_status
     *
     * @param replyStatus the value for product_comments.reply_status
     *
     * @mbg.generated
     */
    public void setReplyStatus(Integer replyStatus) {
        this.replyStatus = replyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.reply_content
     *
     * @return the value of product_comments.reply_content
     *
     * @mbg.generated
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.reply_content
     *
     * @param replyContent the value for product_comments.reply_content
     *
     * @mbg.generated
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.reply_time
     *
     * @return the value of product_comments.reply_time
     *
     * @mbg.generated
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.reply_time
     *
     * @param replyTime the value for product_comments.reply_time
     *
     * @mbg.generated
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_comments.is_show
     *
     * @return the value of product_comments.is_show
     *
     * @mbg.generated
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_comments.is_show
     *
     * @param isShow the value for product_comments.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }
}