package com.example.wiki.domain;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.List;

/**
 * Database Table Remarks:
 *   商品
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product
 */
public class ProductVo {

    private List<ProductImg> productImg;

    public List<ProductImg> getProductImg() {
        return productImg;
    }

    public void setProductImg(List<ProductImg> productImg) {
        this.productImg = productImg;
    }

    /**
     * Database Column Remarks:
     *   商品主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   分类外键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     * Database Column Remarks:
     *   一级分类外键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.root_category_id
     *
     * @mbg.generated
     */
    private Integer rootCategoryId;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sold_num
     *
     * @mbg.generated
     */
    private Integer soldNum;

    /**
     * Database Column Remarks:
     *   状态：1正常  0下架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_status
     *
     * @mbg.generated
     */
    private Integer productStatus;

    /**
     * Database Column Remarks:
     *   商品内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.root_category_id
     *
     * @return the value of product.root_category_id
     *
     * @mbg.generated
     */
    public Integer getRootCategoryId() {
        return rootCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.root_category_id
     *
     * @param rootCategoryId the value for product.root_category_id
     *
     * @mbg.generated
     */
    public void setRootCategoryId(Integer rootCategoryId) {
        this.rootCategoryId = rootCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sold_num
     *
     * @return the value of product.sold_num
     *
     * @mbg.generated
     */
    public Integer getSoldNum() {
        return soldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sold_num
     *
     * @param soldNum the value for product.sold_num
     *
     * @mbg.generated
     */
    public void setSoldNum(Integer soldNum) {
        this.soldNum = soldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_status
     *
     * @return the value of product.product_status
     *
     * @mbg.generated
     */
    public Integer getProductStatus() {
        return productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_status
     *
     * @param productStatus the value for product.product_status
     *
     * @mbg.generated
     */
    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content
     *
     * @return the value of product.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content
     *
     * @param content the value for product.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.update_time
     *
     * @return the value of product.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.update_time
     *
     * @param updateTime the value for product.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}