package com.example.wiki.domain;

import java.time.LocalDateTime;
import java.util.Date;

/**
 * Database Table Remarks:
 *   商品图片
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_img
 */
public class ProductImg {

    @Override
    public String toString() {
        return "ProductImg{" +
                "id='" + id + '\'' +
                ", itemId=" + itemId +
                ", url='" + url + '\'' +
                ", sort=" + sort +
                ", isMain=" + isMain +
                ", createTime=" + createTime +
                ", updateTime=" + updateTime +
                '}';
    }
    /**
     * Database Column Remarks:
     *   图片主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   商品外键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.item_id
     *
     * @mbg.generated
     */
    private Integer itemId;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   是否主图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.is_main
     *
     * @mbg.generated
     */
    private Integer isMain;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_img.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.id
     *
     * @return the value of product_img.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.id
     *
     * @param id the value for product_img.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.item_id
     *
     * @return the value of product_img.item_id
     *
     * @mbg.generated
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.item_id
     *
     * @param itemId the value for product_img.item_id
     *
     * @mbg.generated
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.url
     *
     * @return the value of product_img.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.url
     *
     * @param url the value for product_img.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.sort
     *
     * @return the value of product_img.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.sort
     *
     * @param sort the value for product_img.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.is_main
     *
     * @return the value of product_img.is_main
     *
     * @mbg.generated
     */
    public Integer getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.is_main
     *
     * @param isMain the value for product_img.is_main
     *
     * @mbg.generated
     */
    public void setIsMain(Integer isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.create_time
     *
     * @return the value of product_img.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.create_time
     *
     * @param createTime the value for product_img.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_img.update_time
     *
     * @return the value of product_img.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_img.update_time
     *
     * @param updateTime the value for product_img.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}