package com.example.wiki.domain;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   购物车
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table shopping_cart
 */
public class ShoppingCart {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.cart_id
     *
     * @mbg.generated
     */
    private String cartId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     * Database Column Remarks:
     *   skuid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.sku_id
     *
     * @mbg.generated
     */
    private String skuId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   购物车商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.cart_num
     *
     * @mbg.generated
     */
    private String cartNum;

    /**
     * Database Column Remarks:
     *   添加购物车时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.cart_time
     *
     * @mbg.generated
     */
    private LocalDateTime cartTime;

    /**
     * Database Column Remarks:
     *   添加购物车时商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.product_price
     *
     * @mbg.generated
     */
    private String productPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.cart_id
     *
     * @return the value of shopping_cart.cart_id
     *
     * @mbg.generated
     */
    public String getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.cart_id
     *
     * @param cartId the value for shopping_cart.cart_id
     *
     * @mbg.generated
     */
    public void setCartId(String cartId) {
        this.cartId = cartId == null ? null : cartId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.product_id
     *
     * @return the value of shopping_cart.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.product_id
     *
     * @param productId the value for shopping_cart.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.sku_id
     *
     * @return the value of shopping_cart.sku_id
     *
     * @mbg.generated
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.sku_id
     *
     * @param skuId the value for shopping_cart.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.cart_num
     *
     * @return the value of shopping_cart.cart_num
     *
     * @mbg.generated
     */
    public String getCartNum() {
        return cartNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.cart_num
     *
     * @param cartNum the value for shopping_cart.cart_num
     *
     * @mbg.generated
     */
    public void setCartNum(String cartNum) {
        this.cartNum = cartNum == null ? null : cartNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.cart_time
     *
     * @return the value of shopping_cart.cart_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCartTime() {
        return cartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.cart_time
     *
     * @param cartTime the value for shopping_cart.cart_time
     *
     * @mbg.generated
     */
    public void setCartTime(LocalDateTime cartTime) {
        this.cartTime = cartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.product_price
     *
     * @return the value of shopping_cart.product_price
     *
     * @mbg.generated
     */
    public String getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.product_price
     *
     * @param productPrice the value for shopping_cart.product_price
     *
     * @mbg.generated
     */
    public void setProductPrice(String productPrice) {
        this.productPrice = productPrice == null ? null : productPrice.trim();
    }
}