package com.example.wiki.domain;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   登录历史表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_login_history
 */
public class UserLoginHistory {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   地区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_history.login_time
     *
     * @mbg.generated
     */
    private LocalDateTime loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.ID
     *
     * @return the value of user_login_history.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.ID
     *
     * @param id the value for user_login_history.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.area
     *
     * @return the value of user_login_history.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.area
     *
     * @param area the value for user_login_history.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.country
     *
     * @return the value of user_login_history.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.country
     *
     * @param country the value for user_login_history.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.user_id
     *
     * @return the value of user_login_history.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.user_id
     *
     * @param userId the value for user_login_history.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.ip
     *
     * @return the value of user_login_history.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.ip
     *
     * @param ip the value for user_login_history.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_history.login_time
     *
     * @return the value of user_login_history.login_time
     *
     * @mbg.generated
     */
    public LocalDateTime getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_history.login_time
     *
     * @param loginTime the value for user_login_history.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(LocalDateTime loginTime) {
        this.loginTime = loginTime;
    }
}