package com.example.wiki.domain;

import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   用户地址
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_addr
 */
public class UserAddr {
    /**
     * Database Column Remarks:
     *   地址主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.addr_id
     *
     * @mbg.generated
     */
    private Integer addrId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   收件人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     * Database Column Remarks:
     *   收件人手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   区县
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.area
     *
     * @mbg.generated
     */
    private String area;

    /**
     * Database Column Remarks:
     *   详细地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.addr
     *
     * @mbg.generated
     */
    private String addr;

    /**
     * Database Column Remarks:
     *   邮编
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.post_code
     *
     * @mbg.generated
     */
    private String postCode;

    /**
     * Database Column Remarks:
     *   状态：1正常，0无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   是否默认地址 1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.common_addr
     *
     * @mbg.generated
     */
    private Integer commonAddr;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_addr.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.addr_id
     *
     * @return the value of user_addr.addr_id
     *
     * @mbg.generated
     */
    public Integer getAddrId() {
        return addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.addr_id
     *
     * @param addrId the value for user_addr.addr_id
     *
     * @mbg.generated
     */
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.user_id
     *
     * @return the value of user_addr.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.user_id
     *
     * @param userId the value for user_addr.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.receiver_name
     *
     * @return the value of user_addr.receiver_name
     *
     * @mbg.generated
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.receiver_name
     *
     * @param receiverName the value for user_addr.receiver_name
     *
     * @mbg.generated
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName == null ? null : receiverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.receiver_mobile
     *
     * @return the value of user_addr.receiver_mobile
     *
     * @mbg.generated
     */
    public String getReceiverMobile() {
        return receiverMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.receiver_mobile
     *
     * @param receiverMobile the value for user_addr.receiver_mobile
     *
     * @mbg.generated
     */
    public void setReceiverMobile(String receiverMobile) {
        this.receiverMobile = receiverMobile == null ? null : receiverMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.province
     *
     * @return the value of user_addr.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.province
     *
     * @param province the value for user_addr.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.city
     *
     * @return the value of user_addr.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.city
     *
     * @param city the value for user_addr.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.area
     *
     * @return the value of user_addr.area
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.area
     *
     * @param area the value for user_addr.area
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.addr
     *
     * @return the value of user_addr.addr
     *
     * @mbg.generated
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.addr
     *
     * @param addr the value for user_addr.addr
     *
     * @mbg.generated
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.post_code
     *
     * @return the value of user_addr.post_code
     *
     * @mbg.generated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.post_code
     *
     * @param postCode the value for user_addr.post_code
     *
     * @mbg.generated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.status
     *
     * @return the value of user_addr.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.status
     *
     * @param status the value for user_addr.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.common_addr
     *
     * @return the value of user_addr.common_addr
     *
     * @mbg.generated
     */
    public Integer getCommonAddr() {
        return commonAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.common_addr
     *
     * @param commonAddr the value for user_addr.common_addr
     *
     * @mbg.generated
     */
    public void setCommonAddr(Integer commonAddr) {
        this.commonAddr = commonAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.create_time
     *
     * @return the value of user_addr.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.create_time
     *
     * @param createTime the value for user_addr.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_addr.update_time
     *
     * @return the value of user_addr.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_addr.update_time
     *
     * @param updateTime the value for user_addr.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }
}