package com.example.wiki.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table websites
 */
public class Websites {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websites.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   站点名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websites.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websites.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   Alexa 排名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websites.alexa
     *
     * @mbg.generated
     */
    private Integer alexa;

    /**
     * Database Column Remarks:
     *   国家
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websites.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websites.id
     *
     * @return the value of websites.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websites.id
     *
     * @param id the value for websites.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websites.name
     *
     * @return the value of websites.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websites.name
     *
     * @param name the value for websites.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websites.url
     *
     * @return the value of websites.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websites.url
     *
     * @param url the value for websites.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websites.alexa
     *
     * @return the value of websites.alexa
     *
     * @mbg.generated
     */
    public Integer getAlexa() {
        return alexa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websites.alexa
     *
     * @param alexa the value for websites.alexa
     *
     * @mbg.generated
     */
    public void setAlexa(Integer alexa) {
        this.alexa = alexa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websites.country
     *
     * @return the value of websites.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websites.country
     *
     * @param country the value for websites.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }
}