package com.example.wiki.mapper;

import com.example.wiki.domain.Ebook;
import java.util.List;

public interface EbookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated
     */
    int insert(Ebook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated
     */
    Ebook selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated
     */
    List<Ebook> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ebook
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ebook record);
}