package com.example.wiki.mapper;

import com.example.wiki.domain.IndexImg;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface IndexImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbg.generated
     */
    int insert(IndexImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbg.generated
     */
    IndexImg selectByPrimaryKey(String imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbg.generated
     */
    List<IndexImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndexImg record);

    // 查询轮播图信息
    List<IndexImg> selectIndexImg();
}