package com.example.wiki.mapper;

import com.example.wiki.domain.ProductParams;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ProductParamsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbg.generated
     */
    int insert(ProductParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbg.generated
     */
    ProductParams selectByPrimaryKey(String paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbg.generated
     */
    List<ProductParams> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_params
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductParams record);

    List<ProductParams> selectByProductId(@Param("productId") String productId);
}