package com.example.wiki.mapper;

import com.example.wiki.domain.ProductComments;
import java.util.List;

public interface ProductCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    int insert(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    ProductComments selectByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    List<ProductComments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductComments record);
}