package com.example.wiki.mapper;

import com.example.wiki.domain.ProductComments;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface ProductCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    int insert(ProductComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    ProductComments selectByPrimaryKey(String commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    List<ProductComments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_comments
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductComments record);

    List<ProductComments> getCommentsByProductId(@Param("productId") String productId);

    /**
     * 模糊查询评论
     */
    List<ProductComments> selectCommentsByKeyword(@Param("params") Map<String,Object> params);
}