package com.example.wiki.mapper;

import com.example.wiki.domain.Websites;
import java.util.List;

public interface WebsitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated
     */
    int insert(Websites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated
     */
    Websites selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated
     */
    List<Websites> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Websites record);
}